site_name: Documentation
theme: 
  name: 'rtd-dropdown'
  collapse_by_default: true
# use_directory_urls: true
repo_url: https://github.com/genepattern/gpnotebook-website-docs
extra:
  version: 1.0
site_favicon: favicon/favicon.ico
plugins:
  - search
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
#     - toc:
#         baselevel: 5
  
nav:
  - 'index.md'
  - 'GenePattern Notebook Homepage': 'http://notebook.genepattern.org'
  - Documentation:
    - 'programmatic.md'
    - 'local-installation.md'
    - 'jupyter-users.md'
    - 'releases.md'
    - 'faq.md'
    - 'contact.md'
  
